#!/usr/bin/env python3
"""region_js_sync.py — index.html 의 지역 i18n 블록을 region_norm.py(단일 정본)에서 재생성해 주입한다.

수동 편집 금지: UI 사전이 파이프라인과 어긋나면 지역이 다시 한글로 튄다(2026-10-06 사고).
"""
import datetime as dt
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from region_norm import js_block  # noqa: E402

BASE = r"D:\Hermes\camnemi-crm"
IDX = os.path.join(BASE, "index.html")
BEGIN = "  /* REGION_I18N:BEGIN — generated by backend/region_norm.py --js-block (do not edit by hand) */"
END = "  /* REGION_I18N:END */"

# 최초 1회: 기존 하드코딩 두 줄을 마커 블록으로 교체
OLD = re.compile(
    r'  const LOC_EN = \{[^\n]*\};\n  function locEn\(l\)\{ return LOC_EN\[l\] \|\| l \|\| \'\'; \}',
)


def main():
    html = open(IDX, encoding="utf-8").read()
    blk = BEGIN + "\n" + js_block() + END
    if BEGIN in html and END in html:
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), blk, html, flags=re.S)  # type: ignore
        mode = "markers"
    else:
        if not OLD.search(html):
            raise SystemExit("index.html 에서 기존 LOC_EN/locEn 블록을 찾지 못했습니다 — 수동 확인 필요")
        new = OLD.sub(lambda m: blk, html, count=1)
        mode = "first-run"
    if new == html:
        print("변경 없음(이미 최신)")
        return
    ts = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    bdir = os.path.join(r"D:\Hermes\_sjcu", f"region_backup_{ts}")
    os.makedirs(bdir, exist_ok=True)
    shutil.copy2(IDX, os.path.join(bdir, "index.html"))
    open(IDX, "w", encoding="utf-8", newline="").write(new)
    print(f"[{mode}] index.html 지역 블록 주입 완료 (백업 {bdir})")


if __name__ == "__main__":
    main()